### PR TITLE
Stability analysis: add number of roots for Davidson solver

### PR DESCRIPTION
**Pull request by ajz34**
Hi devs!

## Problem description

I just found for a varity of radicals, wavefunction stability analysis does not show correct judgement.
This is because not enough number of roots are required for davidson solver (orbital hessian diagonalization). Then this solver may not give the lowest eigenvalue in some cases.

## Reporduction of this problem

An example could be molecule F2 (spin=0).

```python
from pyscf import gto, scf
from pyscf.scf.stability import rhf_external

if __name__ == '__main__':
    mol = gto.Mole(atom="F; F 1 1.4113", basis="6-31G").build()
    mf = scf.RHF(mol).run()
    rhf_external(mf)
```

Before this pull request, stability found minimum excitation for RHF->UHF instability is 0.07058134 Hartree and thus F2 is stable. This may be not correct.

To show this value, one need to debug program at https://github.com/pyscf/pyscf/blob/0df2ead0cc9b80a1b8bf0f26b5d1755baf1a472f/pyscf/scf/stability.py#L388.

## After this PR

When set logger level as debug, we may see lowest three eigenvalues to be
```
rhf_external: lowest eigs (e3) of H = [-0.10795055  0.07058127  0.07058504]
```
This gives correct RHF->UHF instability of F2 molecule.

Variable `STAB_NROOTS` indicates space of davidson solver for stability check. I hardcoded this value to be 3.
It seems that recommended value of number of roots are: QChem 2; ORCA 3; Gaussian 6 first time, 3 second time.

## Additional notes

This PR modification will increase computational resources for stability analysis.

Convergence criteria of lowest eigenvalue in PySCF is prehaps 1e-4 amplitude (`tol=1e-4`).
Criteria of Gaussian seems to be extremely loose (0.01 eV). In example of ORCA manual, this value is 1e-4 Hartree.

So maybe efficiency of stability check in PySCF can be further elevated by tatics of convergence.

### CODE REVIEW

**Comment by hebrewsnabla** [comment]
I agree. I've observed similar issue from insufficient roots before, too.

>Convergence criteria of lowest eigenvalue in PySCF is prehaps 1e-4 amplitude (tol=1e-4).
Criteria of Gaussian seems to be extremely loose (0.01 eV).

I think 1e-4 is loose enough. And in some edge cases it's not tight enough. So I made it an option in [this PR](https://github.com/pyscf/pyscf/pull/1416).

**Comment by ndattani** [comment]
There's [2 failed tests](https://github.com/pyscf/pyscf/actions/runs/4053968364/jobs/6975224388#step:4:7391) for the first CI build:
```
FAILED pyscf/scf/test/test_stability.py::KnownValues::test_uhf_stability - As...
FAILED pyscf/scf/test/test_stability.py::KnownValues::test_uhf_stability_with_status
=== 2 failed, 2239 passed, 163 deselected, 28 warnings in 4149.25s (1:09:09) ===
Error: Process completed with exit code 1.
```
Did you try to run all the tests (and make sure they pass) before opening the pull request?

**Comment by ajz34** [comment]
@ndattani I'd admit that I didn't run tests before this PR. Thanks for reminder!

I suggest to lower the criteria threshold of unittests in `scf.test.test_stability`.

Before this additional commit (22e6485), tests does not pass when evaluating overlap between original molecular coefficients `mf1.mo_coeff` and initial guess after stability check for external UHF `mo_e`.
This overlap changes a bit (up to about 1e-6) when increasing number of roots `STAB_NROOTS` from 1 to 3.

For my view, this overlap change is quite minor, as well as initial guess still gives correct ground state after GHF SCF process; so loosen the threshold of overlap check does not invalidates purpose of this unittest.

**Comment by ndattani** [comment]
I see that you got the tests to pass by [changing the testing criteria in the test itself, from matching 6 digits to matching only 5 digits](https://github.com/pyscf/pyscf/pull/1587/commits/22e648596d5fe242874bfed3bdd2d35247d202a3#diff-25f3d04c4af1ec4e06a1229b21f09f76f890161baad08759a4e1e90ca33143adL220) for `s`:
```
s = mf1.det_ovlp(mo_e, mf1.mo_coeff, mf1.mo_occ, mf1.mo_occ,mf1.get_ovlp())[0]
```
Why is it that this `ovlp` can't be made to agree in 6 digits when you make `STAB_NROOTS = 3`?

**Comment by ajz34** [comment]
@ndattani I couldn't fully resolve your concern currently. Some new problem found, and may occur in function `lib.davidson1`; and I don't know how to handle that.

------

The reason of `ovlp` can't be made to agree in 6 digits, is that this test almostly must run when `nroots = 1` as well as `tol = 1e-4` for davidson solver. Otherwise, test may fail. even increasing threshold of davidson solver (giving more precise eigen solution) can fail.

To demonstrate this, I extracted and modified some source codes from PySCF, in the following collapsed code block. Function `deviate` refers to deviate of the molecular orbital coefficient overlap between computed result and known value.

<details>
<summary>Definition of function `deviate`</summary>

```python
from pyscf import gto, scf, lib
import numpy
import numpy as np
import scipy
from pyscf.scf.stability import _gen_hop_uhf_external
from pyscf.soscf import newton_ah
from pyscf.lib import logger

np.set_printoptions(6, suppress=True, linewidth=150)


def uhf_external(mf, with_symmetry=True, verbose=None, return_status=False, tol=1e-4, nroots=1):
    log = logger.new_logger(mf, verbose)
    hop1, hdiag1, hop2, hdiag2 = _gen_hop_uhf_external(mf, with_symmetry)
    stable = True

    def precond(dx, e, x0):
        hdiagd = hdiag2 - e
        hdiagd[abs(hdiagd)<1e-8] = 1e-8
        return dx/hdiagd
    x0 = numpy.zeros_like(hdiag2)
    x0[hdiag2>1e-5] = 1. / hdiag2[hdiag2>1e-5]
    if not with_symmetry:  # allow to break point group symmetry
        x0[numpy.argmin(hdiag2)] = 1
    e3, v = lib.davidson(hop2, x0, precond, tol=tol, nroots=nroots, verbose=log)
    if nroots != 1:
        e3, v = e3[0], v[0]
    log.debug('uhf_external: lowest eigs of H = %s', e3)
    mo = scipy.linalg.block_diag(*mf.mo_coeff)
    if e3 < -1e-5:
        log.note(f'{mf.__class__} wavefunction has an UHF/UKS -> GHF/GKS instability.')
        occidxa = numpy.where(mf.mo_occ[0]> 0)[0]
        viridxa = numpy.where(mf.mo_occ[0]==0)[0]
        occidxb = numpy.where(mf.mo_occ[1]> 0)[0]
        viridxb = numpy.where(mf.mo_occ[1]==0)[0]
        nocca = len(occidxa)
        nvira = len(viridxa)
        noccb = len(occidxb)
        nvirb = len(viridxb)
        nmo = nocca + nvira
        dx = numpy.zeros((nmo*2,nmo*2))
        dx[viridxa[:,None],nmo+occidxb] = v[:nvira*noccb].reshape(nvira,noccb)
        dx[nmo+viridxb[:,None],occidxa] = v[nvira*noccb:].reshape(nvirb,nocca)
        u = newton_ah.expmat(dx - dx.conj().T)
        mo = numpy.dot(mo, u)
        mo = numpy.hstack([mo[:,:nocca], mo[:,nmo:nmo+noccb],
                           mo[:,nocca:nmo], mo[:,nmo+noccb:]])
        stable = False
    else:
        log.note(f'{mf.__class__} wavefunction is stable in the UHF/UKS -> '
                 'GHF/GKS stability analysis')
    return mo, stable, e3, v


def uhf_external_exact(mf, with_symmetry=True, verbose=None, return_status=False):
    log = logger.new_logger(mf, verbose)
    hop1, hdiag1, hop2, hdiag2 = _gen_hop_uhf_external(mf, with_symmetry)
    stable = True

    dim = hdiag2.size
    h = np.zeros((dim, dim))
    for i in range(dim):
        vi = np.zeros(dim)
        vi[i] = 1
        h[i] = hop2(vi)
    e3, v = np.linalg.eigh(h)
    v = v.T
    e3, v = e3[0], v[0]
    log.debug('uhf_external: lowest eigs of H = %s', e3)
    mo = scipy.linalg.block_diag(*mf.mo_coeff)
    if e3 < -1e-5:
        log.note(f'{mf.__class__} wavefunction has an UHF/UKS -> GHF/GKS instability.')
        occidxa = numpy.where(mf.mo_occ[0]> 0)[0]
        viridxa = numpy.where(mf.mo_occ[0]==0)[0]
        occidxb = numpy.where(mf.mo_occ[1]> 0)[0]
        viridxb = numpy.where(mf.mo_occ[1]==0)[0]
        nocca = len(occidxa)
        nvira = len(viridxa)
        noccb = len(occidxb)
        nvirb = len(viridxb)
        nmo = nocca + nvira
        dx = numpy.zeros((nmo*2,nmo*2))
        dx[viridxa[:,None],nmo+occidxb] = v[:nvira*noccb].reshape(nvira,noccb)
        dx[nmo+viridxb[:,None],occidxa] = v[nvira*noccb:].reshape(nvirb,nocca)
        u = newton_ah.expmat(dx - dx.conj().T)
        mo = numpy.dot(mo, u)
        mo = numpy.hstack([mo[:,:nocca], mo[:,nmo:nmo+noccb],
                           mo[:,nocca:nmo], mo[:,nmo+noccb:]])
        stable = False
    else:
        log.note(f'{mf.__class__} wavefunction is stable in the UHF/UKS -> '
                 'GHF/GKS stability analysis')
    return mo, stable, e3, v


def deviate(mo):
    global mf_ghf
    ovlp_known_value = 0.57993272190912937
    return mf_ghf.det_ovlp(
        mo, mf_ghf.mo_coeff, mf_ghf.mo_occ, mf_ghf.mo_occ, mf_ghf.get_ovlp())[0] - ovlp_known_value
```
</details>

Then we see that, either adding `nroots` or decreasing `tol`, or both, will give about 8e-7 deviation, which usually changes a 6th digit.

```python
# note: symmetry = 1
mol = gto.M(atom='O 0 0 0; O 0 0 1.2222', basis='631g*', symmetry=1,
            spin=2, verbose=5, output='/dev/null')
mf = scf.ROHF(mol).run(conv_tol=1e-12)
mf = mf.to_uks()
mf_ghf = mf.to_ghf()

deviate(uhf_external(mf)[0])
# 1.3322676295501878e-15
deviate(uhf_external(mf, tol=1e-12)[0])
# 8.503216496480448e-07
deviate(uhf_external(mf, nroots=3)[0])
# 8.76435113594809e-07
deviate(uhf_external(mf, nroots=144, tol=1e-12)[0])
# -0.4577170240997388; this may be erronuous
deviate(uhf_external_exact(mf)[0])
# 8.503105437540626e-07
```

I guess that known value `0.57993272190912937` unittest is generated by condition `nroots = 1` and `tol = 1e-4`, which is approximately correct but not exact. The better reference value should be `0.5799335722196731`.

But I think, that since stability check only requires to provide qualitatively correct stability and initial mo_coeff guess, this level (8e-7 in mo_coeff overlap) of precision loss is tolarable. I still think that matching only 5 digits does not invalidates purpose of this unittest.

------

But I'd note that if increases `nroots` to 144, this example of ROHF/6-31G* dioxygen with symmetry will fail, as the code above shows. I'm not sure whether this is numerical instability or internal error of `lib.davidson1`.

If symmetry is set to False (C1), then no problem occurs.

```python
# note: symmetry = 0
mol = gto.M(atom='O 0 0 0; O 0 0 1.2222', basis='631g*', symmetry=0,
            spin=2, verbose=5, output='/dev/null')
mf = scf.ROHF(mol).run(conv_tol=1e-12)
mf = mf.to_uks()
mf_ghf = mf.to_ghf()

deviate(uhf_external(mf)[0])
# 5.6036550242222205e-06
deviate(uhf_external(mf, tol=1e-12)[0])
# 8.49294683247237e-07
deviate(uhf_external(mf, nroots=3)[0])
# 8.864743483716353e-08
deviate(uhf_external(mf, nroots=144, tol=1e-12)[0])
# 8.503105506374453e-07; this is the correct value
deviate(uhf_external_exact(mf)[0])
# 8.503105519697129e-07
```

**Comment by hebrewsnabla** [comment]
> But I'd note that if increases nroots to 144, this example of ROHF/6-31G* dioxygen with symmetry will fail, as the code above shows.

I can't reproduce this. It works well. Is your eigenvalue in this case looks right?

**Comment by ajz34** [comment]
@hebrewsnabla This error seems to be always showing on my own PC. But after some check, on another linux server, in most cases there's no error (but still occasionally error occurs) ... 😵 I'm not sure why this happens on my PC. Maybe math libraries.

**Comment by hebrewsnabla** [comment]
Anyway, that's another problem, has nothing to do with the change of this PR.

**Comment by ndattani** [comment]
> "The reason of `ovlp` can't be made to agree in 6 digits, is that this test almostly must run when `nroots = 1` as well as `tol = 1e-4` for davidson solver. "

I don't know enough to see why that's the case. Hopefully others will be able to give more helpful comments on your pull request!

**Comment by ajz34** [comment]
Will be resolved in https://github.com/pyscf/pyscf/pull/1416. I suggest to close this pull request.

**Pull request closed without merging**
