### PR TITLE
fix and activate W391

### PR DESCRIPTION
**Pull request by fchapoton**
another fix, for empty lines near the end of files ;

NOT activated as a new check in the linter ;

done using the script autopep8

### CODE REVIEW

**Comment by PhilipVinc** [comment]
If I may suggest, a big chunk of the python community is moving from pycodestyle/flak8 to ruff, which is better and has an auto fix option which makes it much less cumberstone to use.

to set it up reliably you just need to include a pyproject.toml file with a section [like that](https://github.com/netket/netket/blob/044fa10f451d609c71c1adec48e49342db20d5ba/pyproject.toml#L144) and then you can run it with `ruff check pyscf --fix`.

**Comment by sunqm** [comment]
The empty lines at the end of a file is not a problem IMO. It does not help clarify the code

**Comment by fchapoton** [comment]
so, would you merge if I disactivate the check in the linter ?

**Comment by sunqm** [comment]
I don't think it is necessary to enable W391. I will merge if there are fixes after removing the check of W391.

**Comment by fchapoton** [comment]
ok, here is a branch which does not activate the check for W391

**Review by sunqm — APPROVED** [review]

**Pull request merged**
