### PR TITLE
Adds make_rdm2 to RHF and UHF

### PR DESCRIPTION
**Pull request by Majokux**
Mean-field 2-RDMs factorize into products of the 1-RDM, so typically we don't care to build them,
but sometimes I find it useful to have them at hand to quickly compare to correlated results, etc.
For this reason I suggest to add `make_rdm2` methods to the SCF classes.

### CODE REVIEW

**Review by sunqm — APPROVED** [review]

**Comment by fishjojo** [comment]
please fix lint errors. thanks

**Comment by Majokux** [comment]
>please fix lint errors. thanks

Done. But do we really think that 

```
dm2aa = (numpy.einsum('ij,kl->ijkl', dm1a, dm1a)
         - numpy.einsum('ij,kl->iklj', dm1a, dm1a))
dm2bb = (numpy.einsum('ij,kl->ijkl', dm1b, dm1b)
         - numpy.einsum('ij,kl->iklj', dm1b, dm1b))
```

is easier to read than

```
dm2aa = (numpy.einsum('ij,kl->ijkl', dm1a, dm1a)
       - numpy.einsum('ij,kl->iklj', dm1a, dm1a))
dm2bb = (numpy.einsum('ij,kl->ijkl', dm1b, dm1b)
       - numpy.einsum('ij,kl->iklj', dm1b, dm1b))
```
?

**Comment by sunqm** [comment]
I think your old format looks better. Could you add E128 to the session "ignore" in pyscf/.flake8 configure?

**Comment by Majokux** [comment]
>I think your old format looks better. Could you add E128 to the session "ignore" in pyscf/.flake8 configure?

OK, done

**Pull request merged**
