### PR TITLE
fix bug in IAO, add possible k point sampling for IAO

### PR DESCRIPTION
**Pull request by zhcui**
See also the issue #294

### CODE REVIEW

**Comment by gkc1000** [comment]
Before I can accept this pull request, please update the failing tests (see the travis-CI log).

**Comment by zhcui** [comment]
There are strange randomness or numerical instability in the `test_localizer.py` , which makes the test sometimes fail. However, I do not change anything related to this test file.  Also I do not see a random part in the script.

**Comment by zhcui** [comment]
Hi Qiming,

@sunqm 

Could you take a look at `test_localizer.py`, which seems not always passing even without the pull request I made?

Best,
Zhihao

**Comment by sunqm** [comment]
The failure of test_localizer is caused by the Boys localization. It does randomly converge to a local solution. I should update it at some point. Your code should be fine

**Comment by zhcui** [comment]
Hi Qiming,

Thanks for your reply. 

Just for curiosity: Is there any randomness in Boys and PM if the default guess is 'atomic'? My feeling is that the solution should be deterministic. 

Best,
Zhihao

**Comment by gkc1000** [comment]
Typically things are not completely deterministic if there are multiple
threads due to different roundoff error when different orders of threads
complete.

**Comment by zhcui** [comment]
Thanks, Garnet.

BTW: the pull request is now merged only to the master branch, and should it be merged to dev as well?

Best,
Zhihao

**Comment by sunqm** [comment]
Zhihao, I'll update the dev branch in my next PR to dev

Qiming

On Fri, Mar 15, 2019 at 01:43:55AM -0700, Zhihao Cui wrote:
> Thanks, Garnet.
> 
> BTW: the pull request is now merged only to the master branch, and should it be
> merged to dev as well?
> 
> Best,
> Zhihao
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

-- 
Dr. Qiming Sun
Principal Researcher, Tencent Quantum Laboratory

**Pull request merged**
