### PR TITLE
ao2mo from scalar integral to complex GHF orbitals

### PR DESCRIPTION
**Pull request by xubwa**
As mentioned in #697, a integral transformation for scalar integrals to complex GHF orbitals is desired, this implementation is based on modifying the r_ao2mo.c and retains a similar structure with that and I put all the functions in a new file called nrr_ao2mo.c and add a corresponding nrr_ao2mo.py in pyscf/ao2mo directory. The nrr_ao2mo.py also deals with scalar integral transform to spinor basis so that it also speeds up the spinor integral transformation.
Since PySCF is now in the process of releasing 2.1.0, this PR can wait until the 2.1.0 release finalizes and does not go into this 2.1.0, but I would like to put it here so that people can have a look at it and have some useful suggestion on how the interface should look like.  @sunqm @fishjojo

### CODE REVIEW

**Comment by xubwa** [comment]
@fishjojo Hi Xing, I think this PR is ready to merge, but I seemed to have messed up the commit history when merge the master branch from my side and the authors of a bunch of commits get polluted. Should I close this pr and start a new one or it does not matter?
Best,
Xubo

**Comment by fishjojo** [comment]
@xubwa You can rebase your branch

**Comment by xubwa** [comment]
@fishjojo @sunqm It's ready to be reviewed now.

**Review by sunqm — APPROVED** [review]

**Comment by sunqm** [comment]
* Pleas add a small test to run the nrr_outcore.general function

**Pull request merged**
