### PR TITLE
Addition of (k,-k)-symmetry addon for KSCF

### PR DESCRIPTION
**Pull request by maxnus**
When performing k-point sampled SCF calculations with PySCF, the symmetry between the MO \phi(k) and the conjugated MO \phi(-k)* is frequently being broken. Often, one would like to retain this symmetry, which for example should be an exact symmetry in crystals with centrosymmetry. As an example, this is the default behaviour in VASP, see the entry for `ISYM=0` [here](https://www.vasp.at/wiki/index.php/ISYM). Retaining this symmetry also allows the solution to remain real-orbital supercell representable (see also issue #1161).

Ideally, this symmetry should be implemented in a larger effort to support point-group symmetry in crystals and sampling of the irreducible BZ only. However, this is a somewhat larger project and I am not sure if work is already being done in this direction.
Since I require (k,-k)-symmetric solution for some of my work, I instead implemented a more lightweight solution, allowing the decoration of `KRHF` and `KUHF` according to the addon syntax: `kmf = pyscf.pbc.scf.addons.kconj_symmetry_(kmf)`.
I think this could be useful for more people, until there is proper support for spacegroup symmetry.

An example is given in `pyscf/examples/pbc/43-kconj-symmetry.py`. Most of the code here is orthogonal to other parts of PySCF; the notable exception to this are the routines `get_occ` in `pbc/scf/khf.py` and  `pbc/scf/kuhf.py`.
These routines are currently buggy, in that the lead to a wrong number of occupied MOs, if an **exact** (i.e. to machine precision) degeneracy is present at the Fermi-level. I modified these functions, to crash out in this case instead (which is still better than stealthily changing the number of electrons).

As an alternative, `get_occ` could fill as many of the degenerate orbitals at the Fermi level, as there are remaining electrons, in the hope that the degeneracy only exists temporarily during the SCF loop and will disappear in the following iterations. However, an exact degeneracy is unlikely to occur when not explicitly enforcing symmetry and I thus didn't modify `get_occ` in this way for the time being.

### CODE REVIEW

**Comment by zhcui** [comment]
Hi Max,

I think this is already implemented in the [kpoints-symmetry branch.](https://github.com/pyscf/pyscf/tree/kpoint_symm)

**Comment by januseriksen** [comment]
Hi @maxnus, what's the status of this PR? Or has a similar option been implemented elsewhere, @zhcui? If so, how to enforce this type of _(k,-k)_-symmetry in an KSCF simulation? Cheers to both of you.

**Comment by zhcui** [comment]
You may try something like:
```
kmesh = [3, 3, 3]
kpts_symm = cell.make_kpts(kmesh, with_gamma_point=True, space_group_symmetry=False, time_reversal_symmetry=True)                  
```

**Review by sunqm — APPROVED** [review]

**Comment by verena-neufeld** [comment]
Since kpts symm has been merged and there is a workaround posted by @zhcui , I wonder whether this PR should be altered? I'm saying that without having had a close look at this PR.

**Comment by fishjojo** [comment]
I'm going to close this PR as time-reversal and space-group symmetries are already available in pyscf. Please feel free to contribute your code to [pyscf-forge](https://github.com/pyscf/pyscf-forge) if it adds additional functionalities. And we can merge it with to the main source code once appropriate.

**Pull request closed without merging**
