### PR TITLE
Linear dependency treatment for IAOs

### PR DESCRIPTION
**Pull request by Majokux**
I'm frequently using IAOs and encountered two problems with the current code:

1) For large basis sets, where the AO overlap is (numerically) singular, the Cholesky decomposition of this overlap matrix will fail; this is especially common in solids. In cases where the CD fails, I added a backup inversion, a la canonical orthogonalization, i.e. removing (almost) linearly dependent eigenvectors according to some threshold `lindep_threshold`
[I actually think options for linear-dependency treatment, such as method and threshold, should be attached to the `mole`/`cell` object, as it crops up in multiple locations, but this is another discussion].
 
 2) If at some k-point (or in one spin channel, for a 1e-system), there are not occupied orbitals, the call to `vec_lowdin` will fail
 (there are no orbitals to orthogonalize). I added an early return to deal with this case.
 
Lastly, the IAO construction for molecules and for solids at a given k-point is the same; previously the code was just copied,
 with a k-point loop in the case for solids, but to reduce code duplication I put it into a function, which is being looped over for k-points.

### CODE REVIEW

**Review by sunqm — APPROVED** [review]

**Comment by susilehtola** [comment]
Does it make sense to duplicate the code in scf.addons?

**Comment by Majokux** [comment]
>Does it make sense to duplicate the code in scf.addons?
Sorry, which duplicated code to you mean?

**Comment by susilehtola** [comment]
> > Does it make sense to duplicate the code in scf.addons?
> 
> Sorry, which duplicated code to you mean?

Handling of linear dependencies. Canonical orthogonalization is implemented in `scf.addons.canonical_orth_`, but the addons also have more robust methods i.e. partial Cholesky orthonormalization.

My biggest problem with PySCF is that linear dependencies are an issue in many routines, especially RI based ones as the `(I|J)` matrix is often less well conditioned than the AO overlap matrix!

**Comment by Majokux** [comment]
@susilehtola Makes sense, I changed the PR to use `scf.addons.canonical_orth_` instead.

**Review by zhcui — APPROVED** [review]

**Comment by zhcui** [comment]
should `x.T` in line `p12 = numpy.linalg.multi_dot((x, x.T, s12))` be` x.conj().T`?

**Comment by Majokux** [comment]
>should x.T in line p12 = numpy.linalg.multi_dot((x, x.T, s12)) be x.conj().T?
Yes indeed, thanks bringing this up

**Comment by susilehtola** [comment]
> should `x.T` in line `p12 = numpy.linalg.multi_dot((x, x.T, s12))` be` x.conj().T`?

or just `x.H`

**Pull request merged**
