### PR TITLE
The missing quadrature adjustment in treutler_ahlrichs radial grids

### PR DESCRIPTION
**Pull request by sunqm**
Related to issue #2178

### CODE REVIEW

**Comment by sunqm** [comment]
Does this change look reasonable to you @KarimAED ?

**Comment by KarimAED** [comment]
Yes, this makes sense to me

**Comment by susilehtola** [comment]
IMHO the atomic radius adjustment should be factored out of the radial rule, since the equations are the same for all rules: scale radius by $r_i \to Rr_i$ and weight by $w_i \to R^3 w_i$.

**Comment by sunqm** [comment]
> IMHO the atomic radius adjustment should be factored out of the radial rule, since the equations are the same for all rules: scale radius by ri→Rri and weight by wi→R3wi.

I don't understand your suggestion. Do you suggest to apply the adjustment parameters for all radius grids schemes, not just the Treutler-Ahlrichs grids?

**Comment by susilehtola** [comment]
> > IMHO the atomic radius adjustment should be factored out of the radial rule, since the equations are the same for all rules: scale radius by ri→Rri and weight by wi→R3wi.
> 
> I don't understand your suggestion. Do you suggest to apply the adjustment parameters for all radius grids schemes, not just the Treutler-Ahlrichs grids?

Yes, using the same atomic radii for all stages of the DFT quadrature: both radial grid generation and pruning. The scaling relations are the same regardless of the way the radial grid is generated, so using a common implementation saves effort and removes code duplication.

**Comment by KarimAED** [comment]
Hmm, I'm not sure if I agree 100% @susilehtola. I think the code duplication is quite minimal, and I think there is some added value in the code following the original sources more closely.

Note, however, that I am speaking not as a regular maintainer, but as someone who recently tried to get their head wrapped around the code. In that sense, I am biased towards a more verbose code structure, so feel free to ignore my opinions.

**Comment by susilehtola** [comment]
The problem I see is that if you use inconsistent atomic radii in different parts of the code, you are bound to get some weird results...

**Comment by sunqm** [comment]
@KarimAED Treutler-Ahlrichs grids are fixed. To ensure compatibility to old versions, the old grids scheme is still used as the default . You can add a config line in `pyscf_conf.py` to explicitly enable the fixed grid scheme.

In the next board meeting, we should discuss whether to switch to the fixed grids @ssh2 @gkc1000 @sanshar @tberkel

**Review by fishjojo — APPROVED** [review]

**Pull request merged**
