### PR TITLE
Reset CASSCF stepsize scheduler in kernel

### PR DESCRIPTION
**Pull request by MatthewRHermes**
Address an impurity in the CASSCF kernel functions by resetting the class member _max_stepsize (issue #1762). This variable is set to a number that gets smaller and smaller as kernel proceeds, and if it's too small then nothing will ever converge.

### CODE REVIEW

**Comment by MatthewRHermes** [comment]
Here I choose to explicitly reinitialize `_max_stepsize` as close as possible to the scheduler calls in all relevant kernel functions (even though, as I say in #1762, I suspect the "problem" is a typo in only one of them), because I think it's better to just be 100% certain that this is always being reset.

**Comment by sunqm** [comment]
What about adding a reset method in CASSCF class and placing these initialization there? This method calls the reset method of CASCI class and cleanup attributes like `_max_stepsize`. Also, the reset method should be called in the CASSCFS_Scanner .

**Comment by MatthewRHermes** [comment]
CASCI.reset calls _scf.reset, which erases the cached _eri array, which is necessary for potential energy scans or geometry optimizations, but doesn't that throw the baby out with the bathwater for the case in #1762? To fix that example, CASSCF.reset would have to be called in every kernel run, which doesn't look like how reset is used elsewhere.

Now that I'm saying this, why is casscf._max_stepsize an attribute of casscf at all, given the way it's used? Especially since the scheduler's return is assigned to `max_stepsize` in the local namespace of the calling kernel function? Wouldn't it be more parsimonious to just compare `self.max_stepsize` directly to `envs['max_stepsize']` in the scheduler?

**Comment by MatthewRHermes** [comment]
I suppose the floating max_stepsize is convenient to keep around as metadata, but one could still tag it in a "read-only" sort of way, comparing `self.max_stepsize` to `envs['max_stepsize']` to set its value and then only copying that value to `self._max_stepsize`.

**Comment by MatthewRHermes** [comment]
Like, how about this? The scheduler tags the constricted _max_stepsize on the method instance, and a very advanced user can use this information, but the scheduler itself manipulates the local max_stepsize from the caller scope directly, so that the tag is implicitly reset every kernel call without needing to write an initialization line or a reset function or anything else. Also, the UCASSCF scheduler function imports the RCASSCF function so they will always be identical.

**Comment by MatthewRHermes** [comment]
I suspect that GCISD test failure for Python 3.11 is unrelated to this PR.

**Comment by MatthewRHermes** [comment]
Since @sunqm asked, I also implemented a reset function that additionally resets the _max_stepsize tag. I also took the opportunity to make sure UCASSCF follows the RCASSCF behavior in the scanner and to make sure that CASCI reset gets called in its as_scanner method.

**Comment by MatthewRHermes** [comment]
I'll just add that one reason I like my current solution is that it moves the CASSCF method class closer to the standard that

> Intermediate status at runtime are **not** supposed to be saved in the method class (in contrast to the object oriented paradigm).

From [here](https://pyscf.org/code-rule.html#api-conventions).

**Review by sunqm — APPROVED** [review]

**Pull request merged**
