### PR TITLE
fix_blas_libcint: remove duplicated definition of BLAS library

### PR DESCRIPTION
**Pull request by acastanedam**
New versions of cmake (>3.19) lead to compilation problems due the use
of both definitions `BLA_VENDOR` and `BLAS_LIBRARIES`. Removing the
former fix this issue and it is compatible with older cmake versions.

### CODE REVIEW

**Comment by jamesETsmith** [comment]
@acastanedam thanks for bringing this up, would you mind including a partial or complete copy of the error here? I think it'd help other people who might run into this issue in the near future.

**Comment by sunqm** [comment]
The next version of libcint will drop the dependence to BLAS library. So likely this patch will not be needed in the future.

**Comment by jamesETsmith** [comment]
@acastanedam, thanks for looking into this. CMake converting semicolons into spaces was the same problem I ran into when I tried out this PR. They should be fixed by #1077.

**Comment by acastanedam** [comment]
Hi @jamesETsmith, @sunqm, then everything is working, I guess we can close the MR. Thanks for checking

**Comment by jamesETsmith** [comment]
@acastanedam, thanks for pointing this out, we appreciate the help!

**Pull request closed without merging**
