### PR TITLE
Add boolean flag for stability functions and an example for stability-check loop

### PR DESCRIPTION
**Pull request by hebrewsnabla**
* Add boolean flag for each stability function in `scf.stability`. Now `uhf_internal()` will return `mo, stable`, and `uhf_stability()` will return `mo_i, mo_e, stable_i, stable_e`.
* Add an example for stability-check loop in `examples/scf/17-stability.py`
 related issue #873

### CODE REVIEW

**Comment by Majokux** [comment]
A reasonable change, although it does change the function signature of `mf.stability()`.
And in principle the additional `stable` return value only save one line in a script, i.e. `stable = (mo_i is mf.mo_coeff)`

If we do decide to change the function signature anyway, how about this change:
If stable, `mf.stability()` returns `True` - otherwise it returns the perturbed MOs.

**Comment by hebrewsnabla** [comment]
> A reasonable change, although it does change the function signature of `mf.stability()`.
> And in principle the additional `stable` return value only save one line in a script, i.e. `stable = (mo_i is mf.mo_coeff)`
> 
> If we do decide to change the function signature anyway, how about this change:
> If stable, `mf.stability()` returns `True` - otherwise it returns the perturbed MOs.

I think, in PySCf examples, PySCF recommends calling `mf.stability()` directly and thus it seems that the developers don't care much about the returned value. So I change the number of returned values. Maybe it will bother some users who developing their programs based on this code. But, my changes won't affect something like `mo1 = mf.stability()[0]`, which is also an existent recommended way to call the function.

I think 
> If stable, mf.stability() returns True - otherwise it returns the perturbed MOs.

is a little bit more confusing. And it breaks `mo1 = mf.stability()[0]`.

**Comment by jjgoings** [comment]
> If stable, mf.stability() returns True - otherwise it returns the perturbed MOs.

In addition, it changes output type depending on result which will likely cause problems unless you are careful with type handling. I think adding the additional boolean output is the least disruptive change.

**Comment by sunqm** [comment]
I think changing the returns of this function is acceptable. In case there are users running scripts depending on the old API of this function, what about adding a keyword argument `return_status=False` to control whether to return the status? Then you can obtain the status by passing return_status=True in your code. Please also update the docstring for this optional keyword.

**Comment by hebrewsnabla** [comment]
Everything updated now.

**Review by sunqm — APPROVED** [review]

**Review by sunqm — APPROVED** [review]

**Pull request merged**
