### PR TITLE
Fix biased implementation for the becke radi method

### PR DESCRIPTION
**Pull request by tvogels**
This fixed the Becke radial integration scheme as described in #2490.

### CODE REVIEW

**Comment by sunqm** [comment]
Thanks for the fix. The Becke's 1988 paper states that the radial grids are Gauss-Chebyshev quadrature of the second kind.  The weights in your fix are different to the quadrature from `scipy.special.roots_chebyu` . Are there special treatments in your code?

**Comment by chillenb** [comment]
The Gauss-Chebyshev rules in the NIST handbook Becke apparently used
[out2.pdf](https://github.com/user-attachments/files/17778266/out2.pdf)

are all for doing integrals with the weight function $w(x)=1/\sqrt{1-x^2}$. As @tvogels noticed, Becke must have divided out this weight function without saying anything. The resulting rule (the one in this PR's code) seems to be identical to the [Clenshaw-Curtis formula](https://en.wikipedia.org/wiki/Clenshaw%E2%80%93Curtis_quadrature#Integration_on_infinite_and_semi-infinite_intervals) mapped to $[0,\infty)$, with $L=1$. This follows from

$$\frac{1+\cos{x}}{1-\cos{x}}=\cot^2{\frac{x}{2}}.$$

I agree that `scipy.special.roots_chebyu` can be used for $t$ -- it returns the same values. But for $w$, it won't work without this trick.

**Comment by tvogels** [comment]
Sorry for the delayed response.

Right. I followed the formulas from Wikipedia:

$$
x_i = \cos\left(\frac{i}{n+1}\pi\right),\quad w_i = \frac{\pi}{n+1}\sin^2\left(\frac{i}{n+1}\pi\right),
$$

but added a factor $\frac{1}{\sqrt{1-x^2}} = 1/\sin(\frac{i}{n+1}\pi)$ to the weights to compensate for the fact that this rule gives a weighed integral instead of the desired uniform one.

Becke is indeed not very clear about this in the paper, but something like this must have been implied.

Note that the same treatment appears in the Treutler-Ahlrichs rule:

https://github.com/pyscf/pyscf/blob/2c7f7625fd2719b8f3e9715e40c3937cab65c06e/pyscf/dft/radi.py#L144

https://github.com/pyscf/pyscf/blob/2c7f7625fd2719b8f3e9715e40c3937cab65c06e/pyscf/dft/radi.py#L146

which is also reported to be based on the Gauss-Chebyshev quadrature of the second kind.

**Review by sunqm — APPROVED** [review]

**Comment by tvogels** [comment]
What’s your typical strategy for breaking changes like this?

**Comment by sunqm** [comment]
If the code contains a bug, we then fix the bug and update the corresponding tests. In this case, it seems that the Becke radii code I implemented earlier might have a problem, as the integration of weights appears to be incorrect.

**Pull request merged**
