### PR TITLE
add pycodestyle to linter workflow

### PR DESCRIPTION
**Pull request by fchapoton**
also refreshing the linter on the way

This may help to make progress on #1833

### CODE REVIEW

**Comment by fchapoton** [comment]
the existing flake linter reveals an issue

**Comment by verena-neufeld** [comment]
Is your plan to merge this after the current issues highlighted by pycodestyle have been fixed so we can test new code? That might be nicer so that the merge doesn't immediately lead to new test failures on the main branch.

**Comment by fchapoton** [comment]
as you can see in the modified file, pycodestyle is only testing for the E111 warning, which is already fixed, and the pycodestyle linter is green. The plan would be to activate other fixes at the same time that they are fixed, to avoid moving backward.

**Comment by fchapoton** [comment]
could someone please help fix the flake8 warning

```
pyscf/scf/addons.py:125:9: F811 redefinition of unused 'get_grad' from line 73
Error: Process completed with exit code 1.
```

**Comment by verena-neufeld** [comment]
That sounds like a good plan!

**Comment by fchapoton** [comment]
this should be ready to go, please approve and merge if you think this is a good idea

**Comment by fchapoton** [comment]
the CI failure seems not to be related

**Review by sunqm — APPROVED** [review]

**Pull request merged**
