### PR TITLE
Bug fix for Pipek Mezey + Stability check using Jacobi sweep

### PR DESCRIPTION
**Pull request by hongzhouye**
## Bug fix for Pipek Mezey

This PR fixes issue #1984. In particular, the missing factor of 2 in both gradient and Hessian is restored. The erroneous `h_diag` for exponent = 4 is fixed (as a result, some calculations with exponent = 4 require fewer cycles to converge with the new code). The new implementation supports arbitrary exponent (not limited to 2 and 4). Tests are added that examine if the new code generates gradient and Hessian that agree with finite difference.

A bug in the atomic initial guess (in `boys.py`) is also fixed: the molecular `s1e` was used for the pbc case, which is fixed now.

## Stability check of PM orbitals using Jacobi sweep

The second-order CIAH algorithm along with the atomic initial guess used by the PM code can sometimes result in convergence to a local minimum with orbitals that have high symmetry. This occurs for systems as simple as the occupied orbitals of an isolated water molecule. This PR also implements a Jacobi sweep algorithm that can break the said high symmetry in the localized orbitals and help escape from local minima. The cost is roughly two calls of `atomic_pops()`, which is very modest. The orbitals it generates serve as a better initial guess for PM optimization. A typical use case is
```Python
mlo = PM(mol, mo_coeff)
mlo.kernel()
isstable, mo_new = mlo.stability_jacobi()
Whie not isstable:
    mlo.kernel(mo_new)
    isstable, mo_new = mlo.stability_jacobi()
```
Usually one Jacobi check is enough for the subsequent PM optimization to converge to a "stable" minimum (stable w.r.t. Jacobi rotations). Two localized orbitals from water/cc-pVDZ are shown below.

Screenshot 2023-12-04 at 22 53 27

### CODE REVIEW

**Review by sunqm — APPROVED** [review]

**Comment by sunqm** [comment]
I think the CIAH minimization converges to the local minimum probably due to the symmetry. The initial guess in your example are symmetry adapted orbitals. If the initial guess breaks the symmetry in molecular orbitals, the CIAH code should also converge the results the same to the Jacobi sweep.

**Comment by hongzhouye** [comment]
@sunqm thanks! And completely agreed on the initial guess 👍

**Comment by susilehtola** [comment]
Is  #820 also affected by this?

The issue with wrong symmetry is well-known and affects most solvers: orbitals of different symmetries can't mix in the localization. In this case the standard solution is to slightly perturb the initial guess with a random matrix. Should this be done by default?

**Comment by hongzhouye** [comment]
@susilehtola Thanks for the note! I could reproduce #820 and verified that using converged PM orbitals from the this PR (which break the symmetry) as initial guess for Boys localization resolves the problem in #820. This is an indirect solution. A direct solution may use jacobi-sweep Boys to break the symmetry (PR #1648).

Screenshot 2023-12-09 at 11 31 07

**Pull request merged**
