### PR TITLE
FCI wavefunction symmetry

### PR DESCRIPTION
**Pull request by sunqm**
* Support Dinfh and Cinv symmetry in FCI solver
* Fix issue #1517
* Adjust FCI initial guess

### CODE REVIEW

**Comment by sunqm** [comment]
@susilehtola This branch should be able to produce correct symmetry.

**Comment by ndattani** [comment]
@sunqm I guess your commit from yesterday ([da8a25c](https://github.com/pyscf/pyscf/pull/1529/commits/da8a25c13211f48043c38ee9abf4783bfdc05c0c)) fixes the problem?

**Comment by sunqm** [comment]
Yes. This PR is able to generate correct initial guess for any irreps of the cylindrical symmetry. For a few numbers of low lying states in each symmetry sector, the code in this branch can find the correct solution. There still exist numerical issues that may break the symmetry if computing too many excited states. Different techniques are needed to guarantee the symmetry adaption in H*c contraction. This is not solved by this PR.

**Review by fishjojo — APPROVED** [review]

**Comment by ndattani** [comment]
Thanks! Let us test it on some Delta, Phi, Gamma and Eta states and see how far we can go before the numerical issues impede us :) I'm aware of a couple papers on Gamma states that can be used as a benchmark, but Eta states are an uncharted territory from an *ab initio* perspective, as far as I know (at least for molecules containing elements early in the periodic table). 

I'm still hoping to get past [this issue](https://github.com/sunqm/qcint/issues/17) with the basis set I want to use, perhaps by first seeing if I can get the calculation to work with `libcint` instead of `qcint`. Hopefully I'll be done that next week, then can start looking at some highly excited states, though @susilehtola  may have a head start (at least for the basis sets he's using).

**Pull request merged**
