### PR TITLE
Check for empty set bug fix in einsum

### PR DESCRIPTION
**Pull request by verena-neufeld**
Bug fix when checking for empty set when using lib.einsum. I am still working on understanding the einsum functionality better in lib.einsum but this fix seems to speed up some of my calculations. Thanks to @tberkel for helpful explanations.

### CODE REVIEW

**Comment by verena-neufeld** [comment]
This seems to have caused test failures.

**Comment by verena-neufeld** [comment]
I was able to reproduce a segmentation fault on my local machine in "pyscf/lib/gto/test/test_ecp.py", not sure whether this is it, still investigating.

**Comment by sunqm** [comment]
> I was able to reproduce a segmentation fault on my local machine in "pyscf/lib/gto/test/test_ecp.py", not sure whether this is it, still investigating.

May be caused by the size of pre-allocated buffer

**Comment by verena-neufeld** [comment]
Thank you!

**Pull request merged**
