### PR TITLE
idx arg to _contract_rho()

### PR DESCRIPTION
**Pull request by januseriksen**
Simple way of allowing for restricted contractions between ao and dm in _contract_rho()

### CODE REVIEW

**Comment by januseriksen** [comment]
sorry, I naïvely thought the underscore prefix in contract_rho() was meant to indicate that this is a private function... Updated pbc/dft/numint.py as well.

**Comment by januseriksen** [comment]
Sigh, doing too many things at once. Hopefully this last update covers all remaining issues.

**Comment by sunqm** [comment]
Is the mask idx to improve the ao-dm contraction efficiency? Seems better to drop grids when calling eval_gto. Then you don't have to generate a big trunk of AOs in the first place then drop them in eval_rho.

**Comment by januseriksen** [comment]
Hi Qiming,
No, this is not meant to improve upon the efficiency of the contraction. Rather, I wanted to implement Nakai's energy density analysis (EDA) scheme, in which the treatment of the individual contributions to the xc energy involve restricted ao-dm contrations, cf. eqs. 30 & 31 of IJQC 109, 2464 (2009) [https://onlinelibrary.wiley.com/doi/abs/10.1002/qua.22017]. I've got the AOs from a previous call to numint.eval_ao(), and these are all needed in a series of calls to numint.eval_rho() with different idx masks. The proposed way of achieving this was IMO the easiest/most harmless, without cluttering the code in question too much.

**Comment by januseriksen** [comment]
Also, since _contract_rho() is also used in pbc/dft/numint.py, I would argue in favour of removing its underscore prefix as this might indicate that the function is private to dft/numint.py only. Just a thought, I haven't changed this...

**Comment by januseriksen** [comment]
Any news on this one?

**Comment by januseriksen** [comment]
Please see pyscf#848. This PR may be closed once its replacement has been merged in.

**Comment by januseriksen** [comment]
Closing this & pyscf#848.

**Pull request closed without merging**
