### PR TITLE
Remove hardcoded functional lists, ask libxc instead.

### PR DESCRIPTION
**Pull request by susilehtola**
This PR removes hardcoded functional lists, and employs libxc's Python interface instead.

Libxc is also updated to version 4.3.4. No functionals have been lost from libxc, but the schemes in which they are offered has changed a bit.

I have also added a warning in case range-separated functionals with a non-error function kernel are requested, because PySCF does not appear to calculate the exchange integrals correctly.

### CODE REVIEW

**Comment by susilehtola** [comment]
This would resolve #48.

**Comment by sunqm** [comment]
Sorry for the long silence. Merging this PR potentially requires to update the prerequisite version of cmake (from cmake 2 to cmake 3). Updating the prerequisite of the lowest cmake version has been brought to discussion. Merge should be possible in 1.7 release or later version when the compiling prerequisite is updated.

**Comment by susilehtola** [comment]
Actually, since I ended up not using the libxc python interface at all, one does not need to modify the cmake file, which means this could be included in the next release.

**Comment by susilehtola** [comment]
> Sorry for the long silence. Merging this PR potentially requires to update the prerequisite version of cmake (from cmake 2 to cmake 3). Updating the prerequisite of the lowest cmake version has been brought to discussion. Merge should be possible in 1.7 release or later version when the compiling prerequisite is updated.

CMake version 2 should suffice now.

**Comment by sunqm** [comment]
@susilehtola definitions of exchange functionals m05, m052x, m06, m062x, tpss, bloc, and correlation functionals m05, m052x, m06, m062x, tpss are very different to the old version (v3.0.1). Seems some of the differences are caused by the definition in the new functional, like whether to include HF exchange contribution. Is there a way to access the old definition?

**Comment by susilehtola** [comment]
@sunqm what do you mean by "very different" and "whether to include HF exchange contribution"? The earlier versions exposed the worker functions that did not make any sense at all by themselves, because the functionals had been parametrized as hybrids but the worker functionals lacked the exact exchange contribution; see https://tddft.org/programs/libxc/changes/.

When used correctly, the results should be exactly the same as before.

**Comment by sunqm** [comment]
I think I found them in https://gitlab.com/libxc/libxc/blob/master/src/xc_funcs_removed.h .
Are these functional completely not available?

**Comment by sunqm** [comment]
This PR has been merged in dev branch

**Comment by susilehtola** [comment]
> I think I found them in https://gitlab.com/libxc/libxc/blob/master/src/xc_funcs_removed.h .
> Are these functional completely not available?

The old "definitions" were wrong, since they only included the DFT part and not the exact exchange part. It was very confusing having e.g. the worker functionals `mgga_x_m06`, `mgga_c_m06`, and then the actual functional `hyb_mgga_xc_m06`, which differed from `mgga_x_m06,mgga_c_m06` by the exact exchange parameters. One can still "access" the old version by setting exact exchange to zero without scaling what comes out of libxc.

**Pull request closed without merging**
