### PR TITLE
apply "ruff --fix check --select=C40 pyscf"

### PR DESCRIPTION
**Pull request by fchapoton**
to fix many little  details about list comprehension, dict, sets, etc

### CODE REVIEW

**Comment by verena-neufeld** [comment]
Thanks @fchapoton for cleaning up pyscf! Out of interest, why are {} and {:} preferable over set() and dict()?

**Comment by fchapoton** [comment]
well, usually shorter and convenient

**Comment by sunqm** [comment]
As long as python supports the `set()` and `dict()` function, changing to set comprehension and dict comprehension does not look a necessary to me.

**Comment by fchapoton** [comment]
ok, so should I just close the pull request ?

**Comment by sunqm** [comment]
I'll merge this PR. For future PRs, unless updating the deprecated syntax, simply replacing one syntax by another is not encouraged.

**Pull request merged**
