### PR TITLE
ruff auto-fix for UP027

### PR DESCRIPTION
**Pull request by fchapoton**
this is about
`
UP027 [*] Replace unpacked list comprehension with a generator expression
`
and was scripted using
`
ruff --fix --select=UP027 pyscf/
`

### CODE REVIEW

**Comment by sunqm** [comment]
I don't see particular advantages of such changes involving coding style. Unless there are reasons that I did not realize, I tend to reject this update.

**Comment by verena-neufeld** [comment]
Separate comment: I wonder whether we could remove some of the to be ignored rules in .flake8. That is I think maybe we could follow more of the flake8 rules.

**Comment by fchapoton** [comment]
this avoids creating the list, so it is slightly more efficient

**Comment by fchapoton** [comment]
and by the way, the linter `ruff` only suggests code improvements, and not cosmetic code formatting changes.

https://docs.astral.sh/ruff/rules/

**Comment by sunqm** [comment]
I don't think it is a good practice to follow ruff's suggestion in this case. It basically replaces a small list with an iterator. Technically, this optimization depends on CPython versions and it does not always improve performance. In certain CPython versions, there are specialized OP code to unpack a list of two or three elements. The iterator has no performance advantage in these cases. Even the iterator is faster than list comprehension for a few nano seconds, the performance gain here is negligible since the relevant code are only executed a few times. 

I'd suggest to focus on the optimization for the algorithm or architecture. Unless a significant performance improvement, optimization related to coding style should be discouraged.

**Comment by sunqm** [comment]
> Separate comment: I wonder whether we could remove some of the to be ignored rules in .flake8. That is I think maybe we could follow more of the flake8 rules.

As long as the code is clear and easy to read, I think it is acceptable to write pyscf code in any style, not necessarily constrained by flake8 or other style cops. Actually, I wish to add more ignore rules in flake8 and pylint. But I guess that may lead to more arguments.

**Pull request closed without merging**
